apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/launch-stage: BETA
  name: open-interpreter-slack-bot
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        # run.googleapis.com/execution-environment: gen2
    spec:
      timeoutSeconds: 3600
      serviceAccountName: open-interpreter@bizops-394108.iam.gserviceaccount.com
      containers:
        - image: asia-northeast1-docker.pkg.dev/bizops-394108/open-interpreter/bot
          name: bot
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: OPENAI_API_KEY
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: SLACK_BOT_TOKEN
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: SLACK_SIGNING_SECRET
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 1G
              cpu: 1000m
          volumeMounts:
          - mountPath: /work
            name: work_dir
        - image: asia-northeast1-docker.pkg.dev/bizops-394108/open-interpreter/function-runner
          name: function-runner
          resources:
            limits:
              memory: 1G
              cpu: 1000m
          volumeMounts:
          - mountPath: /work
            name: work_dir
      volumes:
      - name: work_dir
        emptyDir:
          sizeLimit: 5Gi
          medium: Memory
